-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 07:47:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Produto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Produto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Produto` DEFAULT CHARACTER SET utf8 ;
USE `Produto` ;

-- -----------------------------------------------------
-- Table `Produto`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Produto`.`CATEGORIA` (
  `idCATEGORIA` 		INT NOT NULL,
  `dsCategoria` 		VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCATEGORIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Produto`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Produto`.`PRODUTOS` (
  `idPRODUTOS` 				INT NOT NULL,
  `dsProduto` 				VARCHAR(45) NOT NULL,
  `preco` 					FLOAT NOT NULL,
  `qtdade` 					INT NOT NULL,
  `foto` 					LONGBLOB NOT NULL,
  `CATEGORIA_idCATEGORIA` 	INT NOT NULL,
  PRIMARY KEY (`idPRODUTOS`),
  -- INDEX `fk_PRODUTOS_CATEGORIA_idx` (`CATEGORIA_idCATEGORIA` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTOS_CATEGORIA`
    FOREIGN KEY (`CATEGORIA_idCATEGORIA`)
    REFERENCES `Produto`.`CATEGORIA` (`idCATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Produto`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Produto`.`CLIENTE` (
  `idCLIENTE` 			INT NOT NULL,
  `nome` 				VARCHAR(100) NOT NULL,
  `email`				VARCHAR(100) NOT NULL,
  `senha` 				VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Produto`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Produto`.`PEDIDOS` (
  `idPEDIDOS` 				INT NOT NULL,
  `data` 					DATE NOT NULL,
  `status` 					VARCHAR(45) NOT NULL,
  `sessao` 					VARCHAR(45) NOT NULL,
  `CLIENTE_idCLIENTE` 		INT NOT NULL,
  PRIMARY KEY (`idPEDIDOS`),
  -- INDEX `fk_PEDIDOS_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOS_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `Produto`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Produto`.`PEDIDOITENS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Produto`.`PEDIDOITENS` (
  `idPEDIDOITENS` 				INT NOT NULL,
  `qtdade` 						INT NOT NULL,
  `preco` 						FLOAT NOT NULL,
  `total` 						FLOAT NOT NULL,
  `PRODUTOS_idPRODUTOS` 		INT NOT NULL,
  `PEDIDOS_idPEDIDOS` 			INT NOT NULL,
  PRIMARY KEY (`idPEDIDOITENS`),
  -- INDEX `fk_PEDIDOITENS_PRODUTOS1_idx` (`PRODUTOS_idPRODUTOS` ASC) VISIBLE,
  -- INDEX `fk_PEDIDOITENS_PEDIDOS1_idx` (`PEDIDOS_idPEDIDOS` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOITENS_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_idPRODUTOS`)
    REFERENCES `Produto`.`PRODUTOS` (`idPRODUTOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDOITENS_PEDIDOS1`
    FOREIGN KEY (`PEDIDOS_idPEDIDOS`)
    REFERENCES `Produto`.`PEDIDOS` (`idPEDIDOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
